"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { ProductUrlForm } from "@/components/product-url-form";

interface RecentSearch {
  url: string;
  title: string;
  platform: string;
  id: string;
  timestamp: number;
}

const FEATURES = [
  {
    title: "Product Analysis",
    description: "Price, ratings, reviews, specs, images, and active deals — all in one view.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
      </svg>
    ),
  },
  {
    title: "Cross-Platform Matching",
    description: "Automatically finds the same product on Amazon and eBay using UPC and smart keyword matching.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" />
      </svg>
    ),
  },
  {
    title: "Comparison Dashboard",
    description: "Side-by-side pricing, ratings, availability, shipping, and offers comparison.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
      </svg>
    ),
  },
  {
    title: "AI-Powered Insights",
    description: "Pros, cons, verdict, price analysis, and buying tips generated by Claude AI.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
      </svg>
    ),
  },
];

const STEPS = [
  { step: "1", title: "Paste a URL", description: "Drop any Amazon or eBay product link" },
  { step: "2", title: "View Analysis", description: "See price, reviews, specs, and matches" },
  { step: "3", title: "Compare & Decide", description: "Get AI-powered buying recommendation" },
];

export default function Home() {
  const [recentSearches, setRecentSearches] = useState<RecentSearch[]>([]);
  const router = useRouter();

  useEffect(() => {
    const stored = localStorage.getItem("recentSearches");
    if (stored) {
      try {
        setRecentSearches(JSON.parse(stored));
      } catch {
        // ignore
      }
    }
  }, []);

  return (
    <div className="flex min-h-screen flex-col items-center bg-background px-4 pt-20 pb-12">
      {/* Hero */}
      <div className="flex flex-col items-center gap-4 text-center mb-8">
        <div className="flex items-center gap-2 mb-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary">
            <svg className="h-5 w-5 text-primary-foreground" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5" />
            </svg>
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Product Compare
          </h1>
        </div>
        <p className="max-w-lg text-lg text-muted-foreground">
          Compare products across Amazon and eBay. Get structured analysis,
          cross-platform matches, and AI-powered buying advice — instantly.
        </p>
      </div>

      {/* URL Input */}
      <ProductUrlForm />

      {/* How it works */}
      <div className="mt-16 w-full max-w-2xl">
        <h2 className="mb-6 text-center text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          How it works
        </h2>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
          {STEPS.map((s) => (
            <div key={s.step} className="flex flex-col items-center gap-2 text-center">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">
                {s.step}
              </div>
              <h3 className="text-sm font-semibold">{s.title}</h3>
              <p className="text-xs text-muted-foreground">{s.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Features */}
      <div className="mt-16 w-full max-w-3xl">
        <h2 className="mb-6 text-center text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Features
        </h2>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {FEATURES.map((feature) => (
            <Card key={feature.title} className="border-muted">
              <CardContent className="flex gap-4 p-4">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground">
                  {feature.icon}
                </div>
                <div>
                  <h3 className="text-sm font-semibold">{feature.title}</h3>
                  <p className="mt-1 text-xs text-muted-foreground leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Recent searches */}
      {recentSearches.length > 0 && (
        <div className="mt-16 w-full max-w-2xl">
          <h2 className="mb-4 text-sm font-medium text-muted-foreground">
            Recent Searches
          </h2>
          <div className="space-y-2">
            {recentSearches.map((search) => (
              <button
                key={search.id}
                onClick={() => {
                  const stored = sessionStorage.getItem(`product:${search.id}`);
                  if (stored) {
                    router.push(`/product/${search.id}`);
                  }
                }}
                className="flex w-full items-center gap-3 rounded-lg border p-3 text-left transition-colors hover:bg-muted/50"
              >
                <span
                  className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium ${
                    search.platform === "amazon"
                      ? "bg-orange-100 text-orange-700"
                      : "bg-blue-100 text-blue-700"
                  }`}
                >
                  {search.platform === "amazon" ? "Amazon" : "eBay"}
                </span>
                <span className="line-clamp-1 text-sm">{search.title}</span>
                <span className="ml-auto shrink-0 text-xs text-muted-foreground">
                  {new Date(search.timestamp).toLocaleDateString()}
                </span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="mt-16 text-center text-xs text-muted-foreground">
        Built with Next.js, Tailwind CSS, and Claude AI
      </div>
    </div>
  );
}
